#!/usr/bin/env python3
"""
Genera index-standalone.html a partir de index.html, inlineando todas las
imágenes locales como data URI con base64.

Optimización por formato (mismas reglas que aplican al standalone manual):
  - PNG   → PNG-8 paleta (256 colores), max 1200 px   (illustrations)
  - JPEG  → q=82 progressive, max 1600 px
  - WEBP  → q=82, max 1600 px
  - SVG   → sin tocar (ya son pequeños)

Los originales en disco NO se modifican.

Uso:
  python3 build_standalone.py                       # index.html → index-standalone.html
  python3 build_standalone.py -i otro.html -o out   # custom in/out
  python3 build_standalone.py --no-optimize         # inline sin re-encodear

Requisito: Pillow (`pip install Pillow`).
"""
from __future__ import annotations

import argparse
import base64
import io
import re
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit('Pillow no está instalado. Ejecuta: pip install Pillow')

# Coincide con literales entrecomillados que apunten a ./images/... o images/...
# Acepta comillas ' o ", espacios, caracteres unicode en la ruta.
PATH_RE = re.compile(
    r"""(['"])(\.?\/?images\/[^'"]+?\.(?:png|jpg|jpeg|webp|svg))\1""",
    re.IGNORECASE,
)


def _to_rgb(img: Image.Image) -> Image.Image:
    """Baja a RGB salvo que la alfa esté realmente en uso."""
    if img.mode == 'RGBA':
        if img.split()[-1].getextrema()[0] >= 255:
            return img.convert('RGB')
        return img
    if img.mode in ('LA', 'P'):
        return img.convert('RGB')
    if img.mode != 'RGB':
        return img.convert('RGB')
    return img


def _resize(img: Image.Image, max_dim: int) -> Image.Image:
    if max(img.size) > max_dim:
        img = img.copy()
        img.thumbnail((max_dim, max_dim), Image.LANCZOS)
    return img


def optimize_png(data: bytes) -> bytes:
    img = Image.open(io.BytesIO(data))
    img = _to_rgb(img)
    img = _resize(img, 1200)
    pal = img.quantize(colors=256,
                       method=Image.Quantize.MEDIANCUT,
                       dither=Image.Dither.FLOYDSTEINBERG)
    buf = io.BytesIO()
    pal.save(buf, format='PNG', optimize=True)
    return buf.getvalue()


def optimize_jpeg(data: bytes) -> bytes:
    img = Image.open(io.BytesIO(data))
    img = _to_rgb(img)
    img = _resize(img, 1600)
    buf = io.BytesIO()
    img.save(buf, format='JPEG', quality=82, optimize=True, progressive=True)
    return buf.getvalue()


def optimize_webp(data: bytes) -> bytes:
    img = Image.open(io.BytesIO(data))
    img = _to_rgb(img)
    img = _resize(img, 1600)
    buf = io.BytesIO()
    img.save(buf, format='WEBP', quality=82, method=6)
    return buf.getvalue()


# Passthrough para SVG
def optimize_svg(data: bytes) -> bytes:
    return data


OPTIMIZERS = {
    'png':  ('image/png',     optimize_png),
    'jpg':  ('image/jpeg',    optimize_jpeg),
    'jpeg': ('image/jpeg',    optimize_jpeg),
    'webp': ('image/webp',    optimize_webp),
    'svg':  ('image/svg+xml', optimize_svg),
}


def build(src: Path, dst: Path, optimize: bool = True) -> None:
    html = src.read_text(encoding='utf-8')
    src_dir = src.parent

    cache: dict[str, str] = {}     # path relativo → data URI
    stats: dict[str, dict[str, int]] = {}  # ext → {count, in, out}

    def repl(m: re.Match) -> str:
        quote = m.group(1)
        rel = m.group(2)
        rel_clean = rel.lstrip('./')

        if rel_clean in cache:
            return f'{quote}{cache[rel_clean]}{quote}'

        full = src_dir / rel_clean
        if not full.exists():
            print(f'  [falta]   {rel}', file=sys.stderr)
            return m.group(0)

        ext = full.suffix.lower().lstrip('.')
        if ext not in OPTIMIZERS:
            print(f'  [ext? {ext}]  {rel}', file=sys.stderr)
            return m.group(0)

        raw = full.read_bytes()
        if optimize:
            mime, opt_fn = OPTIMIZERS[ext]
            opt = opt_fn(raw)
        else:
            mime = OPTIMIZERS[ext][0]
            opt = raw

        uri = f'data:{mime};base64,{base64.b64encode(opt).decode("ascii")}'
        cache[rel_clean] = uri

        s = stats.setdefault(ext, {'count': 0, 'in': 0, 'out': 0})
        s['count'] += 1
        s['in']  += len(raw)
        s['out'] += len(opt)

        ratio = len(raw) / max(len(opt), 1)
        print(f'  {ext:<4} {rel_clean:<55} '
              f'{len(raw)/1024:>7.1f}K → {len(opt)/1024:>7.1f}K  ({ratio:>5.1f}×)')
        return f'{quote}{uri}{quote}'

    new_html = PATH_RE.sub(repl, html)

    # Banner para distinguir el archivo generado
    banner = (
        '<!--\n'
        '  GENERATED by build_standalone.py — no editar a mano.\n'
        '  Edita index.html y vuelve a correr este script.\n'
        '-->\n'
    )
    if '<!DOCTYPE' in new_html:
        new_html = new_html.replace('<!DOCTYPE', banner + '<!DOCTYPE', 1)

    dst.write_text(new_html, encoding='utf-8')

    orig_bytes = len(html.encode('utf-8'))
    new_bytes = len(new_html.encode('utf-8'))

    print()
    print(f'  Salida: {dst}  ({new_bytes/1024/1024:.2f} MB)')
    print(f'  Inline data: {(new_bytes - orig_bytes)/1024/1024:+.2f} MB sobre el HTML base')
    print()
    print('  Por formato:')
    print(f'  {"ext":<6}{"count":>7}{"in":>12}{"out":>12}{"saved":>12}')
    total_in = total_out = 0
    for ext, s in sorted(stats.items()):
        saved = s['in'] - s['out']
        total_in  += s['in']
        total_out += s['out']
        print(f'  {ext:<6}{s["count"]:>7}'
              f'{s["in"]/1024/1024:>10.2f} MB'
              f'{s["out"]/1024/1024:>10.2f} MB'
              f'{saved/1024/1024:>10.2f} MB')
    print(f'  {"TOTAL":<6}{sum(s["count"] for s in stats.values()):>7}'
          f'{total_in/1024/1024:>10.2f} MB'
          f'{total_out/1024/1024:>10.2f} MB'
          f'{(total_in-total_out)/1024/1024:>10.2f} MB')


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('-i', '--input', default='index.html',
                    help='HTML de entrada (default: index.html)')
    ap.add_argument('-o', '--output', default='index-standalone.html',
                    help='HTML de salida (default: index-standalone.html)')
    ap.add_argument('--no-optimize', action='store_true',
                    help='Inlinea sin re-encodear (más rápido, archivo más grande)')
    args = ap.parse_args()

    src = Path(args.input)
    dst = Path(args.output)

    if not src.exists():
        sys.exit(f'No existe el archivo de entrada: {src}')

    print(f'  Origen:  {src}')
    print(f'  Destino: {dst}')
    print(f'  Modo:    {"inline crudo" if args.no_optimize else "optimizado"}')
    print()
    build(src, dst, optimize=not args.no_optimize)


if __name__ == '__main__':
    main()